name: telegram notification
on:
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: notify telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.CHAT_ID }}
          token: ${{ secrets.PANCAKE_BOT_TOKEN }}
          args: New pull request to ${{ github.base_ref }} by ${{ github.actor }} - https://github.com/${{github.repository}}/pulls
